[book]
title = "Long COVID Guide"
authors = ["znwang25"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/"
git-repository-url = "https://github.com/LongCovidGuide/longcovidguide.github.io"
edit-url-template = "https://github.com/LongCovidGuide/longcovidguide.github.io/edit/main/{path}"
